/* Generated by JTB 1.4.9 */
package ch.unibe.iam.scg.javacc.syntaxtree;

import ch.unibe.iam.scg.javacc.visitor.*;

/**
 * JTB node class for the production MainClass:<br>
 * Corresponding grammar:<br>
 * f0 -> <CLASS><br>
 * f1 -> Identifier()<br>
 * f2 -> <BRACE_LEFT><br>
 * f3 -> <PUBLIC_MODIFIER><br>
 * f4 -> <STATIC_MODIFIER><br>
 * f5 -> <VOID_TYPE><br>
 * f6 -> <MAIN_METHOD_NAME><br>
 * f7 -> <PARENTHESIS_LEFT><br>
 * f8 -> <STRING_TYPE><br>
 * f9 -> <BRACKET_LEFT><br>
 * f10 -> <BRACKET_RIGHT><br>
 * f11 -> Identifier()<br>
 * f12 -> <PARENTHESIS_RIGHT><br>
 * f13 -> <BRACE_LEFT><br>
 * f14 -> ( Statement() )?<br>
 * f15 -> <BRACE_RIGHT><br>
 * f16 -> <BRACE_RIGHT><br>
 */
public class MainClass implements INode {

  /** Child node 1 */
  public NodeToken f0;

  /** Child node 2 */
  public Identifier f1;

  /** Child node 3 */
  public NodeToken f2;

  /** Child node 4 */
  public NodeToken f3;

  /** Child node 5 */
  public NodeToken f4;

  /** Child node 6 */
  public NodeToken f5;

  /** Child node 7 */
  public NodeToken f6;

  /** Child node 8 */
  public NodeToken f7;

  /** Child node 9 */
  public NodeToken f8;

  /** Child node 10 */
  public NodeToken f9;

  /** Child node 11 */
  public NodeToken f10;

  /** Child node 12 */
  public Identifier f11;

  /** Child node 13 */
  public NodeToken f12;

  /** Child node 14 */
  public NodeToken f13;

  /** Child node 15 */
  public NodeOptional f14;

  /** Child node 16 */
  public NodeToken f15;

  /** Child node 17 */
  public NodeToken f16;

  /** The serial version UID */
  private static final long serialVersionUID = 149L;

  /**
   * Constructs the node with all its children nodes.
   *
   * @param n0 - first child node
   * @param n1 - next child node
   * @param n2 - next child node
   * @param n3 - next child node
   * @param n4 - next child node
   * @param n5 - next child node
   * @param n6 - next child node
   * @param n7 - next child node
   * @param n8 - next child node
   * @param n9 - next child node
   * @param n10 - next child node
   * @param n11 - next child node
   * @param n12 - next child node
   * @param n13 - next child node
   * @param n14 - next child node
   * @param n15 - next child node
   * @param n16 - next child node
   */
  public MainClass(final NodeToken n0, final Identifier n1, final NodeToken n2, final NodeToken n3, final NodeToken n4, final NodeToken n5, final NodeToken n6, final NodeToken n7, final NodeToken n8, final NodeToken n9, final NodeToken n10, final Identifier n11, final NodeToken n12, final NodeToken n13, final NodeOptional n14, final NodeToken n15, final NodeToken n16) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
    f4 = n4;
    f5 = n5;
    f6 = n6;
    f7 = n7;
    f8 = n8;
    f9 = n9;
    f10 = n10;
    f11 = n11;
    f12 = n12;
    f13 = n13;
    f14 = n14;
    f15 = n15;
    f16 = n16;
  }

  /**
   * Accepts the IRetArguVisitor visitor.
   *
   * @param <R> the user return type
   * @param <A> the user argument type
   * @param vis - the visitor
   * @param argu - a user chosen argument
   * @return a user chosen return information
   */
  @Override
  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  /**
   * Accepts the IRetVisitor visitor.
   *
   * @param <R> the user return type
   * @param vis - the visitor
   * @return a user chosen return information
   */
  @Override
  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  /**
   * Accepts the IVoidArguVisitor visitor.
   *
   * @param <A> the user argument type
   * @param vis - the visitor
   * @param argu - a user chosen argument
   */
  @Override
  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  /**
   * Accepts the IVoidVisitor visitor.
   *
   * @param vis - the visitor
   */
  @Override
  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
